spring:
  cloud:
    gateway:
      mvc:
        routes:
          - id: addressservice
            uri: lb://addressservice
            predicates:
              - Path=/api/v1/addresses/**
          - id: cartservice
            uri: lb://cartservice
            predicates:
              - Path=/api/v1/carts/**
          - id: invoiceservice
            uri: lb://invoiceservice
            predicates:
              - Path=/api/v1/invoice/**
          - id: eureka
            uri: http://localhost:8888
            predicates:
                - Path=/eureka/web
            filters:
                - SetPath=/
          - id: eureka-static
            uri: http://localhost:8888
            predicates:
                - Path=/eureka/**
          - id: identityserver
            uri: lb://identityserver
            predicates:
              - Path=/api/v1/auth/**
          - id: orderservice
            uri: lb://orderservice
            predicates:
              - Path=/api/v1/orders/**
          - id: productservice-product
            uri: lb://productservice
            predicates:
              - Path=/api/v1/products/**
          - id: productservice-catalog
            uri: lb://productservice
            predicates:
              - Path=/api/v1/catalogs/**
          - id: customerservice-customer
            uri: lb://customerservice
            predicates:
              - Path=/api/v1/customers/**
          - id: customerservice-customerInvoice
            uri: lb://customerservice
            predicates:
              - Path=/api/v1/customerInvoices/**
          - id: customerservice-contactMedium
            uri: lb://productservice
            predicates:
              - Path=/api/v1/contactMediums/**
server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true

