spring:
  datasource:
    url: jdbc:postgresql://identity-db-prod:5432/identityservice
    username: postgres
    password: test
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update

server:
  port: 8086
  error:
    include-message: always

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8888/eureka/
    registerWithEureka: true
    fetchRegistry: true


jwt:
  expiration: 600000
  secret: cQis7hFG8pR/i4ZvnVUQrHQJ6oTm2wEcZa5F2r8IryZuqZX3OeEvhXQvVfwkhrxTyZEoUZhSTtetKQKDY2J6t6ArhgO7+0XRVFFM3dE2N2+FKTU3v4ulQBxj3r7s3me4FPXrjgOJPkfJdBFYfQFYl/m28zkS1xzj/V+ZljEJ5u1kZSNVb6ImMAmYqN5U0ULaVRZUXmRYDxRDLBZ/uanIuc7E0FJ0oICLHRaG8lXz0VdoSgpLJrKsYuJaGNVvGvI6odHJec9VQAOIn5Ay5WtmSTb0KLtL5I5MpKdm6P4UgcBfGfd7CY9JR2gNsHlAZH+t/LkwBA75os6UVAbQQu0RPjkJ54sRIlCalvCApuhX36g=
